[package]
name = "secret_sharing"
version = "0.1.0"
authors = ["Austin Tindle <tindleaj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
